baseURL = "https://viorel.me/"
languageCode = "en-us"
title = "Viorel Sfetea"
theme = "tale"

[permalinks]
  posts = "/:year/:slug/"

[outputs]
  home = ["HTML", "RSS"]

[outputFormats]
[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "feed"
